server.port=8080

# ====================== MSSQL ======================
spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=TESTDB;encrypt=true;trustServerCertificate=true
spring.datasource.username=sa
spring.datasource.password=ebbase
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServerDialect

# ====================== LOGGING TO FILE ======================
logging.level.com.example.cards_it=INFO
logging.file.name=logs/application.log
logging.pattern.file=%d{yyyy-MM-dd HH:mm:ss} [%thread] [%logger{72}] [%-5level] - %msg%n

#======================= 3rd Party API Key =====================
stripe.api.key=${STRIPE_SECRET_KEY:YOUR_STRIPE_KEY_HERE}